"""NMEA bridge for a VHF radio: hardware setup and wiring.

The logic lives in hardware-free modules that are tested on a desktop:
  bridge.py  radio path: framing, queue, forward/block policy, detectors, watchdog policy, GPS reader
  ui.py      key events, menu, screen-off timer, redraw
This file only creates the hardware objects, connects them and runs the loop.
"""
import binascii
import gc
import sys
import _thread
import utime

import machine
from machine import Pin, SPI, WDT, UART
from writer import Writer

import jamming
import l76x
import nav
import NMEA
import screens
import settings
import sh1107
import spoofing
import ui
import wificreds
import roboto14
from bridge import Bridge, GpsReader, RawLogger, RxQueue

try:
    import version                  # generated by `make deploy` (git revision)
    VERSION = version.VERSION
except ImportError:
    VERSION = 'dev'
from jamming import JamDetector
from spoofing import SpoofDetector

# Variables
DEBUG = False                     # echo forwarded sentences and module acks to the REPL (blocks if a USB host is attached but not reading)
LONG_PRESS_THRESHOLD = 1 * 1000   # threshold in milliseconds to distinguish between short and long press
WATCHDOG_TIMEOUT = 5 * 1000       # watchdog has to be fed every N milliseconds
WIFI_TOGGLE_PRESS = 3 * 1000      # hold UP this long (ms) to switch the Wi-Fi access point on/off
FORWARD_TYPES_ALL = ('RMC', 'GGA', 'GSA', 'GSV', 'ZDA')  # every type the menu can switch
FORWARD_TYPES = ('RMC', 'GGA', 'GSA', 'GSV', 'ZDA')  # default sentence types forwarded to the radio and Wi-Fi (editable in the menu)
JAM_DETECT = True                 # default for the jamming indicator (see jamming.py); editable in the menu
SPOOF_DETECT = True               # default for the spoofing indicator (see spoofing.py); editable in the menu
SPOOF_ACTION = 'display'          # default: 'display' only shows SPF?/SPF!; 'block' also stops forwarding SPOOF_BLOCK_TYPES during an ALERT
SPOOF_BLOCK_TYPES = ('RMC', 'GGA')
FORWARD_TALKERS = ('GP', 'GN')    # talker IDs forwarded to the radio (BeiDou $BDGSV/$BDGSA are not)
GNSS_MODE = 'GPS+BD'              # 'GPS' or 'GPS+BD' (L76B supports no other constellations)
WIFI_ENABLE = True                # Pico W only: allow the NMEA-over-Wi-Fi access point (off at boot; hold UP to toggle)
WIFI_SSID = ''                    # '' = 'NMEABridge-XXXX' with 4 characters derived from the board's unique ID; or set your own
WIFI_PASSWORD = ''                # '' = random password made on first boot, stored in wifi_password.txt and shown on the Wi-Fi screen; or set your own (8+ characters)
WIFI_COUNTRY = 'SE'               # two-letter regulatory domain of the access point (the firmware default 'XX' failed with Android)
WIFI_CHANNEL = 6                  # 2.4 GHz channel 1-11 (0 = firmware default)
WIFI_PORT = 10110                 # NMEA 0183 over TCP (server) and UDP (broadcast)
WIFI_MAX_CLIENTS = 4
WIFI_FORWARD_TALKERS = ('GP', 'GN', 'BD')
HEAP_REFRESH_MS = 3000           # System page: how often free heap is re-measured (after gc.collect)
MEM_REPORT_PERIOD = 60 * 1000     # print free/used heap this often when DEBUG is on
UARTx = 0                         # GPS UART
GPS_BAUDRATE = 4800               # GPS link rate: 4800, 9600, 14400, 19200, 38400, 57600 or 115200 (module is switched at boot)
FIX_INTERVAL_MS = 1000 if GPS_BAUDRATE <= 4800 else 800  # slow links need a longer fix interval
# Timing knobs of the radio path (stale-fix timeout, watchdog silence timeout, evaluation periods): see bridge.py

# Pins and buses
PIN_OLED_SCK, PIN_OLED_MOSI = 10, 11
PIN_OLED_DC, PIN_OLED_RST, PIN_OLED_CS = 8, 12, 9
OLED_SPI_BAUDRATE = 10_000_000
PIN_KEY_UP, PIN_KEY_DN = 15, 17
RS485_UART = 1                    # must differ from UARTx when both use UART1 pins
RS485_TX, RS485_RX = 4, 5
RS485_BAUDRATE = 4800             # what the VHF radio expects
RS485_TXBUF = 512                 # TX buffer so uart.write doesn't block the main loop

# User settings (menu): the constants above are the defaults, settings.json holds the user's overrides
DEFAULTS = {'gps_baud': GPS_BAUDRATE, 'gnss_mode': GNSS_MODE, 'jam_detect': JAM_DETECT,
            'spoof_detect': SPOOF_DETECT, 'spoof_action': SPOOF_ACTION, 'contrast': 0, 'screen_off_s': 0,
            'log_raw': False}
for _t in FORWARD_TYPES_ALL:
    DEFAULTS['fwd_' + _t] = _t in FORWARD_TYPES
DEFAULTS.update(settings.threshold_defaults(jamming, spoofing))
cfg = settings.Settings(DEFAULTS)
cfg.load()
settings.apply_thresholds(cfg, jamming, spoofing)
GPS_BAUDRATE = cfg.get('gps_baud')    # these two take effect at boot (menu: reboot to apply)
GNSS_MODE = cfg.get('gnss_mode')
FIX_INTERVAL_MS = 1000 if GPS_BAUDRATE <= 4800 else 800

# Display
spi1 = SPI(1, baudrate=OLED_SPI_BAUDRATE, sck=Pin(PIN_OLED_SCK), mosi=Pin(PIN_OLED_MOSI), miso=None)
oled = sh1107.SH1107_SPI(128, 64, spi1, Pin(PIN_OLED_DC), Pin(PIN_OLED_RST), Pin(PIN_OLED_CS), rotate=180)
font_large = Writer(oled, roboto14)
oled.init_display()
if cfg.is_overridden('contrast'):
    oled.contrast(cfg.get('contrast'))  # the driver starts at 0
oled.fill(0)
oled.text('Waiting for fix...', 0, 0, 1)
oled.show()


def report(name, exc):
    """Show a failure on the REPL (never raises)."""
    try:
        print('ERROR in', name)
        sys.print_exception(exc)
    except Exception:
        pass


def fatal(reason):
    print('FATAL:', reason, '- resetting')
    utime.sleep_ms(200)
    machine.reset()


# Key handling: the pin IRQs only debounce, classify and queue; the main loop does the work
events = nav.EventQueue(8)
navigator = nav.Navigator(nav.PAGES if WIFI_ENABLE else tuple(p for p in nav.PAGES if p != nav.PAGE_WIFI))


def make_button_handler(tracker):
    def handler(pin):
        ev = tracker.edge(pin.value(), utime.ticks_ms())
        if ev:
            events.put(ev)
    return handler

key0 = Pin(PIN_KEY_UP, Pin.IN, Pin.PULL_UP)
key1 = Pin(PIN_KEY_DN, Pin.IN, Pin.PULL_UP)
# Register the handler functions for both rising and falling edges
key0.irq(trigger=Pin.IRQ_FALLING | Pin.IRQ_RISING, handler=make_button_handler(
    nav.ButtonTracker('UP', LONG_PRESS_THRESHOLD, WIFI_TOGGLE_PRESS if WIFI_ENABLE else None)))
key1.irq(trigger=Pin.IRQ_FALLING | Pin.IRQ_RISING, handler=make_button_handler(
    nav.ButtonTracker('DN', LONG_PRESS_THRESHOLD)))

# Radio path
nmea_parser = NMEA.Parser()
rx_queue = RxQueue(16, _thread.allocate_lock())
radio = UART(RS485_UART, baudrate=RS485_BAUDRATE, tx=Pin(RS485_TX), rx=Pin(RS485_RX), txbuf=RS485_TXBUF)
radio.init(RS485_BAUDRATE, bits=8, parity=None, stop=1)
core = Bridge(nmea_parser, rx_queue, radio, utime.ticks_ms, on_fatal=fatal,
              log=print if DEBUG else None)
core.report = report
core.forward_talkers = FORWARD_TALKERS
core.wifi_talkers = WIFI_FORWARD_TALKERS
core.block_types = SPOOF_BLOCK_TYPES
core.spoof_action = cfg.get('spoof_action')
core.forward_types = tuple(t for t in FORWARD_TYPES_ALL if cfg.get('fwd_' + t))
if DEBUG:
    core.on_forward = lambda text: print(text.strip())


def disable_raw_log():
    cfg.set('log_raw', False)   # a console that does not drain would stall the loop: switch logging off (not saved)
    core.on_raw = None
    print('Log raw switched off: the console is not keeping up')


def set_raw_log(on):
    core.on_raw = RawLogger(print, utime.ticks_ms, on_disable=disable_raw_log) if on else None


set_raw_log(cfg.get('log_raw'))


def gps_init():
    """Find the GPS module's baud rate, switch it if needed and configure it. Returns the rate it was found at."""
    configured = []
    found = gps.configure_baudrate(GPS_BAUDRATE, prepare=lambda: configured.append(configure_module()))
    avg_load, worst_load = l76x.nmea_load(GPS_BAUDRATE, FIX_INTERVAL_MS, GNSS_MODE == 'GPS+BD')
    if DEBUG:
        print('GPS baud {}: module found at {}'.format(GPS_BAUDRATE, found))
        print('GPS link load: avg {:.0f}%, worst cycle {:.0f}%'.format(avg_load * 100, worst_load * 100))
        if avg_load > 0.8 or worst_load > 1.0:
            print('WARNING: GPS link may be overloaded; raise GPS_BAUDRATE or use GNSS_MODE = GPS')
    if found is None:               # nobody answered: nothing to configure, and the reader will look again later
        gps.config_failed = []
        return None
    if not configured:
        configure_module()
    return found


def configure_module():
    """Send the configuration. Each command waits for the module's acknowledgement (and is resent if it is
    lost): the module drops commands that arrive while it restarts its engine. The acknowledgements are handed
    on as ordinary sentences, so the parser records them (module acks, AIC status). When the module is found
    at another baud rate this runs before the switch (see l76x.configure_baudrate)."""
    failed = gps.send_commands([
        gps.PMTK_API_SET_STOP_QZSS,                 # disable Japanese QZSS
        gps.PMTK_API_SET_SBAS_ENABLED,
        gps.PMTK_API_SET_DGPS_MODE,
        gps.PMTK_ENABLE_EASY,
        l76x.fix_interval_command(FIX_INTERVAL_MS),
        gps.SET_NORMAL_MODE,
        gps.SET_GPS_BEIDOU_SEARCH_MODE if GNSS_MODE == 'GPS+BD' else gps.SET_GPS_SEARCH_MODE,
        gps.SET_SYNC_PPS_NMEA_ON,
        gps.SET_NMEA_OUTPUT,
        gps.PMTK_SET_AIC,
        gps.PMTK_JAM_DETECT_ON,                     # module jamming detector -> $PMTKSPF
    ], on_ack=lambda line: rx_queue.push((utime.ticks_ms(), line + '\r\n')))
    gps.config_failed = failed
    if DEBUG:
        for command, flag in failed:
            print('GPS module did not accept {} (reply: {})'.format(command, flag))


gps = l76x.L76X(uartx=UARTx, _baudrate=GPS_BAUDRATE, verbose=DEBUG)
reader = GpsReader(gps, rx_queue, utime.ticks_ms, gps_init)
core.reader = reader
_thread.start_new_thread(reader.run_forever, (utime.sleep_ms, report))

# Wi-Fi (Pico W): imported and started only when switched on
wifi_ssid = wifi_password = ''
if WIFI_ENABLE:
    wifi_ssid = wificreds.get_ssid(WIFI_SSID)
    wifi_password, wifi_pw_stored = wificreds.get_password(WIFI_PASSWORD)
    if WIFI_PASSWORD and wifi_password != WIFI_PASSWORD:
        print('WARNING: WIFI_PASSWORD must have 8-63 printable ASCII characters; using a generated one')
    if DEBUG and not wifi_pw_stored:
        print('WARNING: could not store the Wi-Fi password; it changes at every boot')
wdt = None                        # armed on the first valid GPS sentence (can't be stopped once started)


def set_wifi(on):
    """Start/stop the access point. wifi.py is imported lazily so the default footprint stays small."""
    if on:
        if core.broadcaster is None:
            import network
            import socket
            import wifi
            core.broadcaster = wifi.NmeaBroadcaster(network, socket, wifi_ssid, wifi_password,
                                                    WIFI_PORT, WIFI_MAX_CLIENTS, WIFI_COUNTRY, WIFI_CHANNEL)
        gc.collect()
        try:
            core.broadcaster.start(feed=wdt.feed if wdt else None, sleep_ms=utime.sleep_ms)
        except Exception as e:  # bad password, AP did not come up, ...
            print('Wi-Fi start failed:', e)
        gc.collect()
    elif core.broadcaster:
        core.broadcaster.stop()
        gc.collect()


def wifi_active():
    return bool(core.broadcaster and core.broadcaster.active)


def wifi_info():
    state, ssid, ip, clients, max_clients = (core.broadcaster.info() if core.broadcaster
                                             else ('OFF', wifi_ssid, '', 0, WIFI_MAX_CLIENTS))
    return state, ssid, ip, clients, max_clients, wifi_password


def memreport(tag):
    gc.collect()
    print('MEM {}: free {} B, used {} B'.format(tag, gc.mem_free(), gc.mem_alloc()))


def make_spoof():
    # GPS time check must tolerate how late a sentence can arrive behind a big GSA/GSV cycle
    return SpoofDetector(nmea_parser,
                         spoofing.TIME_JUMP_MS + l76x.nmea_burst_ms(GPS_BAUDRATE, GNSS_MODE == 'GPS+BD'))


def apply_setting(key):
    """Make a changed live setting take effect (called by the menu)."""
    if key == 'jam_detect':
        core.detector = JamDetector(nmea_parser) if cfg.get(key) else None
    elif key == 'spoof_detect':
        core.spoof = make_spoof() if cfg.get(key) else None
    elif key == 'spoof_action':
        core.spoof_action = cfg.get(key)
    elif key.startswith('fwd_'):
        core.forward_types = tuple(t for t in FORWARD_TYPES_ALL if cfg.get('fwd_' + t))
    elif key == 'contrast':
        oled.contrast(cfg.get(key))
    elif key == 'log_raw':
        set_raw_log(cfg.get(key))
    elif key != 'screen_off_s':   # read every loop; everything else is an advanced threshold
        settings.apply_thresholds(cfg, jamming, spoofing)
        if core.spoof:
            core.spoof.time_tolerance_ms = (spoofing.TIME_JUMP_MS +
                                            l76x.nmea_burst_ms(GPS_BAUDRATE, GNSS_MODE == 'GPS+BD'))


def reset_settings():
    before = dict(cfg.values)
    cfg.reset()
    for key, value in cfg.values.items():
        if value != before[key] and settings.spec(key)[4] == settings.LIVE:
            apply_setting(key)


def regenerate_wifi_password():
    global wifi_password
    if WIFI_PASSWORD:
        print('WIFI_PASSWORD is set in main.py: nothing to regenerate')
        return
    wifi_password, _ = wificreds.regenerate_password()
    if core.broadcaster:
        was_on = core.broadcaster.active
        core.broadcaster.set_password(wifi_password)
        if was_on:  # restart so the new password is in use
            set_wifi(False)
            set_wifi(True)


menu_hooks = {'apply': apply_setting, 'reset': reset_settings, 'reboot': machine.reset}
if WIFI_ENABLE:
    menu_hooks['wifi_active'] = wifi_active
    menu_hooks['wifi_toggle'] = lambda: set_wifi(not wifi_active())
    menu_hooks['regen_password'] = regenerate_wifi_password


def make_menu():
    import menu as menu_mod   # imported only while the menu is open
    return menu_mod.Menu(cfg, menu_hooks)


_heap = [0, None]   # ticks of last reading, free bytes


def free_heap(now_ms):
    """Free heap after a collection (a raw reading swings with the uncollected garbage), refreshed every
    HEAP_REFRESH_MS and rounded down to 4 KiB so it does not force screen redraws."""
    if _heap[1] is None or utime.ticks_diff(now_ms, _heap[0]) >= HEAP_REFRESH_MS:
        gc.collect()
        _heap[0], _heap[1] = now_ms, gc.mem_free() // 4096 * 4096
    return _heap[1]


def system_info():
    inv_base = core.stats['rcv'] or 1
    return {'uptime_s': screen_ui.uptime_ms // 1000, 'heap': free_heap(utime.ticks_ms()),
            'dropped': rx_queue.dropped, 'inv_pct': round(core.stats['inv'] * 100 / inv_base),
            'baud': GPS_BAUDRATE, 'found': reader.found, 'fix_ms': FIX_INTERVAL_MS, 'gnss': GNSS_MODE,
            'uid': binascii.hexlify(machine.unique_id()).decode(), 'now_ms': utime.ticks_ms(),
            'version': VERSION}


core.detector = JamDetector(nmea_parser) if cfg.get('jam_detect') else None
core.spoof = make_spoof() if cfg.get('spoof_detect') else None
screen_ui = ui.UiController(cfg, oled, font_large, screens.draw, navigator, events, core, make_menu,
                            wifi_info, system_info, lambda: set_wifi(not wifi_active()), utime.ticks_ms,
                            menu_timeout_ms=60 * 1000)

utime.sleep(1)  # grace time for the UARTs to start
last_mem_report = utime.ticks_ms()
if DEBUG:
    memreport('boot')

# Main loop. The radio path and the UI are separate: a failure in one must not stop the other, and the
# watchdog is handled outside both.
while True:
    now = utime.ticks_ms()
    try:
        core.step(now)
    except Exception as e:  # core.step contains its own failures; this is the last line of defence
        report('bridge', e)
    try:
        screen_ui.step(now)
    except Exception as e:
        report('ui', e)

    if core.watchdog.should_arm():
        wdt = WDT(timeout=WATCHDOG_TIMEOUT)
        core.watchdog.armed = True
    if wdt and core.watchdog.should_feed(now):
        wdt.feed()

    if DEBUG and utime.ticks_diff(now, last_mem_report) > MEM_REPORT_PERIOD:
        memreport('run')
        last_mem_report = now

    utime.sleep(0.01)  # yield so the GPS thread isn't starved
